CREATE SEQUENCE book_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  MAXVALUE 2147483647
  CACHE 1;

CREATE TABLE book (
  id int8 NOT NULL DEFAULT nextval('book_id_seq'),
  name VARCHAR (255),
  author VARCHAR (255),
  PRIMARY KEY (id));